steps:
  - name: maven:3.6.3-openjdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/e_commerce_planet', '.']
images: ['gcr.io/$PROJECT_ID/e_commerce_planet']